#!/usr/bin/env sh
#. "$(dirname -- "$0")/_/husky.sh"

#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

npm run lint-api && npm run lint-nft-marketplace && npm run lint-libs-dto && npm run lint-libs-contracts
