#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

npm run lint-api-fix && npm run lint-nft-marketplace-fix && npm run lint-libs-dto-fix && npm run lint-libs-contracts-fix && git add -A .
