name: Angular Deploy to S3
on:
    push:
        branches: [ nx-repo-github-actions ]

jobs:
    build:
        runs-on: ubuntu-latest
#        defaults:
#            run:
#                working-directory: apps/nft-marketplace
        steps:
            - name: Checkout source code
              uses: actions/checkout@master

            - name: Cache node modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-
            - name: Install
              run: npm install

#            - name: Lint
#              run: npm run lint

#            - name: Test
#              run: npm run test

            - name: Build
              run: npm run build

            - name: Deploy
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
#                  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
#                  AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
              run: |
                  aws s3 cp \
                    --recursive \
                    --region eu-central-1 \
                    dist/apps/nft-marketplace s3://test-serve
#            - name: Notification
#              uses: 8398a7/action-slack@v2.6.0
#              with:
#                  status: ${{ job.status }}
#                  author_name: Github Actions
#              env:
#                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
