name: Deploy image to ECR
on:
    push:
        branches: [main, build]

jobs:
    build:
        runs-on: ubuntu-latest
        #        defaults:
        #            run:
        #                working-directory: apps/nft-marketplace
        steps:
            - name: Checkout source code
              uses: actions/checkout@master

            - name: Cache node modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-
            - name: Install
              run: npm ci

            - name: Build front end
              run: npm run build

            - name: Build back end
              run: npm run build-api

            - name: Build, tag, and push docker image to Amazon ECR
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
                REGISTRY: 705418884782.dkr.ecr.eu-central-1.amazonaws.com
                REPOSITORY: swan-nft-marketplace
                IMAGE_TAG: ${{ github.sha }}
              run: |
                docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

#            - name: Clear S3 bucket
#              env:
#                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
#                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
#              run: |
#                  aws s3 rm s3://test-serve \
#                    --recursive \
#                    --region eu-central-1
#
#            - name: Deploy
#              env:
#                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
#                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
#              run: |
#                  aws s3 cp \
#                    --recursive \
#                    --region eu-central-1 \
#                    dist/apps/nft-marketplace s3://test-serve

#            - name: Notification
#              uses: 8398a7/action-slack@v2.6.0
#              with:
#                  status: ${{ job.status }}
#                  author_name: Github Actions
#              env:
#                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
